# -*- coding: utf-8 -*-
"""naive_bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qzSinKtne0ToRPxaTJRIqRPXIrW8p3fz
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/titanic.csv")
df.head()

df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

inputs = df.drop('Survived',axis='columns')
target = df.Survived

#inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

inputs.columns[inputs.isna().any()]

inputs.Age[:10]

inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

model.fit(X_train,y_train)

model.score(X_test,y_test)

X_test[0:10]

y_test[0:10]

model.predict(X_test[0:10])

model.predict_proba(X_test[:10])

from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

import matplotlib.pyplot as plt

predicted_probabilities = model.predict_proba(X_train)

# Get the unique class labels.
class_labels = model.classes_

# Create a figure with subplots for each class.
fig, axes = plt.subplots(nrows=len(class_labels), figsize=(10, 5))

# Plot the data for each class.
for i, class_label in enumerate(class_labels):
    # Get the predicted probabilities for the current class.
    class_probabilities = predicted_probabilities[:, i]

    # Plot the data points.
    axes[i].plot(X_train, class_probabilities, linestyle='', marker='.')

    # Set the title and labels for the subplot.
    axes[i].set_title(f'Class {class_label}')
    axes[i].set_xlabel('Feature')
    axes[i].set_ylabel('Probability')

# Show the plot.
plt.tight_layout()
plt.show()